"""update_promotion_model

Revision ID: c9d928fead86
Revises: 03a63d976b35
Create Date: 2025-12-14 12:55:47.797517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d928fead86'
down_revision: Union[str, Sequence[str], None] = '03a63d976b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('code', sa.String(length=50), nullable=True))
    op.add_column('promotions', sa.Column('trigger_type', sa.String(length=50), nullable=False))
    op.add_column('promotions', sa.Column('min_quantity', sa.Integer(), nullable=True))
    op.alter_column('promotions', 'discount_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.create_unique_constraint(op.f('promotions_code_key'), 'promotions', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('promotions_code_key'), 'promotions', type_='unique')
    op.alter_column('promotions', 'discount_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.drop_column('promotions', 'min_quantity')
    op.drop_column('promotions', 'trigger_type')
    op.drop_column('promotions', 'code')
    # ### end Alembic commands ###
