"""update_user_and_order_schema

Revision ID: 03a63d976b35
Revises: e3b18ea219f3
Create Date: 2025-12-13 10:44:12.322197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a63d976b35'
down_revision: Union[str, Sequence[str], None] = 'e3b18ea219f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_mode', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('delivery_cost', sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.add_column('user', sa.Column('title', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('fax_number', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('address_line_1', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('address_line_2', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('zip_code', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(length=50), nullable=True))
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'address',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('user', 'country')
    op.drop_column('user', 'zip_code')
    op.drop_column('user', 'state')
    op.drop_column('user', 'address_line_2')
    op.drop_column('user', 'address_line_1')
    op.drop_column('user', 'fax_number')
    op.drop_column('user', 'title')
    op.drop_column('orders', 'delivery_cost')
    op.drop_column('orders', 'delivery_mode')
    # ### end Alembic commands ###
