"""add product inventory and reviews tables

Revision ID: e464ab934867
Revises: 1639391b7bb4
Create Date: 2025-12-06 18:54:28.358566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e464ab934867'
down_revision: Union[str, Sequence[str], None] = '1639391b7bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('category_pkey'))
    )
    op.create_index(op.f('category_id_idx'), 'category', ['id'], unique=False)
    op.create_index(op.f('category_slug_idx'), 'category', ['slug'], unique=True)
    op.create_table('promotions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('promotions_pkey'))
    )
    op.create_index(op.f('promotions_id_idx'), 'promotions', ['id'], unique=False)
    op.create_table('wine_info',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('alcohol_percentage', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('vintage', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('wine_info_category_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('wine_info_pkey'))
    )
    op.create_index(op.f('wine_info_id_idx'), 'wine_info', ['id'], unique=False)
    op.create_index(op.f('wine_info_name_idx'), 'wine_info', ['name'], unique=False)
    op.create_index(op.f('wine_info_slug_idx'), 'wine_info', ['slug'], unique=True)
    op.create_table('inventory',
    sa.Column('wine_id', sa.UUID(), nullable=False),
    sa.Column('batch_code', sa.String(length=50), nullable=True),
    sa.Column('quantity_available', sa.Integer(), nullable=True),
    sa.Column('import_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('shelf_location', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wine_id'], ['wine_info.id'], name=op.f('inventory_wine_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_pkey'))
    )
    op.create_index(op.f('inventory_id_idx'), 'inventory', ['id'], unique=False)
    op.create_table('product_reviews',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wine_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['product_reviews.id'], name=op.f('product_reviews_parent_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('product_reviews_user_id_fkey')),
    sa.ForeignKeyConstraint(['wine_id'], ['wine_info.id'], name=op.f('product_reviews_wine_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_reviews_pkey'))
    )
    op.create_index(op.f('product_reviews_id_idx'), 'product_reviews', ['id'], unique=False)
    op.create_table('wine_images',
    sa.Column('wine_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('is_thumbnail', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wine_id'], ['wine_info.id'], name=op.f('wine_images_wine_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('wine_images_pkey'))
    )
    op.create_index(op.f('wine_images_id_idx'), 'wine_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('wine_images_id_idx'), table_name='wine_images')
    op.drop_table('wine_images')
    op.drop_index(op.f('product_reviews_id_idx'), table_name='product_reviews')
    op.drop_table('product_reviews')
    op.drop_index(op.f('inventory_id_idx'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('wine_info_slug_idx'), table_name='wine_info')
    op.drop_index(op.f('wine_info_name_idx'), table_name='wine_info')
    op.drop_index(op.f('wine_info_id_idx'), table_name='wine_info')
    op.drop_table('wine_info')
    op.drop_index(op.f('promotions_id_idx'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('category_slug_idx'), table_name='category')
    op.drop_index(op.f('category_id_idx'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
