"""Add new table: chat messages table

Revision ID: 6c72f84d0ab5
Revises: 01f4bdebf7c7
Create Date: 2025-12-29 07:23:22.588792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c72f84d0ab5'
down_revision: Union[str, Sequence[str], None] = '01f4bdebf7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], name=op.f('chat_messages_receiver_id_fkey')),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('chat_messages_sender_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    op.create_index(op.f('chat_messages_id_idx'), 'chat_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('chat_messages_id_idx'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
