"""update_cart_logic

Revision ID: b73dbbf474b6
Revises: 46f3143918e1
Create Date: 2025-12-12 20:23:43.746124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b73dbbf474b6'
down_revision: Union[str, Sequence[str], None] = '46f3143918e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('price_at_add', sa.DECIMAL(precision=12, scale=2), nullable=False))
    op.add_column('carts', sa.Column('session_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('carts_session_id_idx'), 'carts', ['session_id'], unique=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('carts_session_id_idx'), table_name='carts')
    op.drop_column('carts', 'session_id')
    op.drop_column('cart_items', 'price_at_add')
    # ### end Alembic commands ###
