"""add_order_discount

Revision ID: 9f7e74f3ac98
Revises: c9d928fead86
Create Date: 2025-12-14 15:59:48.649543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f7e74f3ac98'
down_revision: Union[str, Sequence[str], None] = 'c9d928fead86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('discount_amount', sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.add_column('orders', sa.Column('promotion_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('orders_promotion_id_fkey'), 'orders', 'promotions', ['promotion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_promotion_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'promotion_id')
    op.drop_column('orders', 'discount_amount')
    # ### end Alembic commands ###
