"""Add import price

Revision ID: e3b18ea219f3
Revises: b73dbbf474b6
Create Date: 2025-12-13 10:18:33.495231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b18ea219f3'
down_revision: Union[str, Sequence[str], None] = 'b73dbbf474b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('import_price', sa.DECIMAL(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'import_price')
    # ### end Alembic commands ###
