"""init

Revision ID: 90826dacf0e9
Revises: 
Create Date: 2025-12-20 14:45:11.855940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90826dacf0e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('category_pkey'))
    )
    op.create_index(op.f('category_id_idx'), 'category', ['id'], unique=False)
    op.create_index(op.f('category_slug_idx'), 'category', ['slug'], unique=True)
    op.create_table('grape_varieties',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('grape_varieties_pkey')),
    sa.UniqueConstraint('name', name=op.f('grape_varieties_name_key'))
    )
    op.create_index(op.f('grape_varieties_id_idx'), 'grape_varieties', ['id'], unique=False)
    op.create_table('promotions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('promotions_pkey')),
    sa.UniqueConstraint('code', name=op.f('promotions_code_key'))
    )
    op.create_index(op.f('promotions_id_idx'), 'promotions', ['id'], unique=False)
    op.create_table('regions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('map_image_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('regions_pkey'))
    )
    op.create_index(op.f('regions_id_idx'), 'regions', ['id'], unique=False)
    op.create_index(op.f('regions_name_idx'), 'regions', ['name'], unique=False)
    op.create_table('user',
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('birthdate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('fax_number', sa.String(length=50), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key')),
    sa.UniqueConstraint('phone_number', name=op.f('user_phone_number_key'))
    )
    op.create_index(op.f('user_id_idx'), 'user', ['id'], unique=False)
    op.create_table('carts',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('carts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('carts_pkey'))
    )
    op.create_index(op.f('carts_id_idx'), 'carts', ['id'], unique=False)
    op.create_index(op.f('carts_session_id_idx'), 'carts', ['session_id'], unique=False)
    op.create_table('orders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('delivery_mode', sa.String(length=50), nullable=True),
    sa.Column('delivery_cost', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discount_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('promotion_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], name=op.f('orders_promotion_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('orders_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    op.create_index(op.f('orders_id_idx'), 'orders', ['id'], unique=False)
    op.create_table('wineries',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('fax_number', sa.String(length=50), nullable=True),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('wineries_region_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('wineries_pkey'))
    )
    op.create_index(op.f('wineries_id_idx'), 'wineries', ['id'], unique=False)
    op.create_index(op.f('wineries_name_idx'), 'wineries', ['name'], unique=False)
    op.create_table('wine_info',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('alcohol_percentage', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('vintage', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('winery_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('wine_info_category_id_fkey')),
    sa.ForeignKeyConstraint(['winery_id'], ['wineries.id'], name=op.f('wine_info_winery_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('wine_info_pkey'))
    )
    op.create_index(op.f('wine_info_id_idx'), 'wine_info', ['id'], unique=False)
    op.create_index(op.f('wine_info_name_idx'), 'wine_info', ['name'], unique=False)
    op.create_index(op.f('wine_info_slug_idx'), 'wine_info', ['slug'], unique=True)
    op.create_table('cart_items',
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('wine_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price_at_add', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('cart_items_cart_id_fkey')),
    sa.ForeignKeyConstraint(['wine_id'], ['wine_info.id'], name=op.f('cart_items_wine_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cart_items_pkey'))
    )
    op.create_index(op.f('cart_items_id_idx'), 'cart_items', ['id'], unique=False)
    op.create_table('inventory',
    sa.Column('wine_id', sa.UUID(), nullable=False),
    sa.Column('batch_code', sa.String(length=50), nullable=True),
    sa.Column('quantity_available', sa.Integer(), nullable=True),
    sa.Column('import_price', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('import_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('shelf_location', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wine_id'], ['wine_info.id'], name=op.f('inventory_wine_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_pkey'))
    )
    op.create_index(op.f('inventory_id_idx'), 'inventory', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('wine_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_purchase', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_items_order_id_fkey')),
    sa.ForeignKeyConstraint(['wine_id'], ['wine_info.id'], name=op.f('order_items_wine_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_items_pkey'))
    )
    op.create_index(op.f('order_items_id_idx'), 'order_items', ['id'], unique=False)
    op.create_table('product_reviews',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wine_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['product_reviews.id'], name=op.f('product_reviews_parent_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('product_reviews_user_id_fkey')),
    sa.ForeignKeyConstraint(['wine_id'], ['wine_info.id'], name=op.f('product_reviews_wine_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_reviews_pkey'))
    )
    op.create_index(op.f('product_reviews_id_idx'), 'product_reviews', ['id'], unique=False)
    op.create_table('wine_grapes',
    sa.Column('wine_id', sa.UUID(), nullable=False),
    sa.Column('grape_variety_id', sa.UUID(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grape_variety_id'], ['grape_varieties.id'], name=op.f('wine_grapes_grape_variety_id_fkey')),
    sa.ForeignKeyConstraint(['wine_id'], ['wine_info.id'], name=op.f('wine_grapes_wine_id_fkey')),
    sa.PrimaryKeyConstraint('wine_id', 'grape_variety_id', 'id', name=op.f('wine_grapes_pkey'))
    )
    op.create_index(op.f('wine_grapes_id_idx'), 'wine_grapes', ['id'], unique=False)
    op.create_table('wine_images',
    sa.Column('wine_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('is_thumbnail', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wine_id'], ['wine_info.id'], name=op.f('wine_images_wine_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('wine_images_pkey'))
    )
    op.create_index(op.f('wine_images_id_idx'), 'wine_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('wine_images_id_idx'), table_name='wine_images')
    op.drop_table('wine_images')
    op.drop_index(op.f('wine_grapes_id_idx'), table_name='wine_grapes')
    op.drop_table('wine_grapes')
    op.drop_index(op.f('product_reviews_id_idx'), table_name='product_reviews')
    op.drop_table('product_reviews')
    op.drop_index(op.f('order_items_id_idx'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('inventory_id_idx'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('cart_items_id_idx'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('wine_info_slug_idx'), table_name='wine_info')
    op.drop_index(op.f('wine_info_name_idx'), table_name='wine_info')
    op.drop_index(op.f('wine_info_id_idx'), table_name='wine_info')
    op.drop_table('wine_info')
    op.drop_index(op.f('wineries_name_idx'), table_name='wineries')
    op.drop_index(op.f('wineries_id_idx'), table_name='wineries')
    op.drop_table('wineries')
    op.drop_index(op.f('orders_id_idx'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('carts_session_id_idx'), table_name='carts')
    op.drop_index(op.f('carts_id_idx'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('user_id_idx'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('regions_name_idx'), table_name='regions')
    op.drop_index(op.f('regions_id_idx'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('promotions_id_idx'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('grape_varieties_id_idx'), table_name='grape_varieties')
    op.drop_table('grape_varieties')
    op.drop_index(op.f('category_slug_idx'), table_name='category')
    op.drop_index(op.f('category_id_idx'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
